# Generated by Django 2.2.5 on 2020-05-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('co_name', models.CharField(max_length=50)),
                ('latest_price', models.FloatField()),
                ('previous_price', models.FloatField()),
                ('pe_ratio', models.FloatField()),
                ('marketcap', models.FloatField()),
                ('change', models.FloatField()),
            ],
        ),
    ]
